accounts/urls.py
from django.urls import path
from .views import SignupView, LoginView,LogoutView

app_name = 'accounts'
urlpatterns = [
    path('signup/', SignupView, name = 'signup'),
    path('login/', LoginView, name = 'login'),
    path('logout/', LogoutView, name='logout')
]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('testapp/', include('testapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testapp/urls.py
from django.urls import path
from .views import BlogView, BlogDetail, AddPost , PostLike, PostUnlike

urlpatterns = [
    path('',BlogView.as_view(), name = 'home'),
    path('blog/<pk>',BlogDetail.as_view(), name='detail'),
    path('additem', AddPost , name='additem'),
    path('like/<postid>', PostLike, name='postlike'),
    path('unlike/<postid>', PostUnlike, name='postunlike'),
]

accounts/models.py
from django.db import models

# Create your models here.

testapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User , on_delete= models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to='%Y/%m/%d', null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='BlogLikes', blank=True)

    def __str__(self):
        return self.title

    def getsnippet(self):
        return self.content[0:30] + '...'

testapp/forms.py
from django import forms

class AddPostForm(forms.Form):
    title = forms.CharField(label='title' , max_length=200)
    content = forms.CharField(label='content' , widget=forms.Textarea)
    image = forms.ImageField()

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponse

def SignupView(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponse('user has been created!')
            
    form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})

def LoginView(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/testapp')
            
    form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})


def LogoutView(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/testapp')

testapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Blog
from .forms import AddPostForm
from django.views import generic


class BlogView(generic.ListView):
    template_name='testapp/Home.html'
    context_object_name='blogpost'

    def get_queryset(self):
        return Blog.objects.all()


class BlogDetail(generic.DetailView):
    model = Blog
    template_name = 'testapp/BlogDetail.html'


def AddPost(request):
    if request.method == "POST":
        form = AddPostForm(request.POST , request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            image = form.cleaned_data['image']

            author = request.user

            blog = Blog.objects.create(title = title , content = content ,author=author, image= image)
            blog.save()
            return HttpResponse('blog post created')
    else:
        form = AddPostForm()
        blog = Blog.objects.all()
    context = {'form': form}
    return render(request, 'testapp/addItem.html',context)


def PostLike(request, postid):
    post = Blog.objects.get(id = postid)
    user = request.user
    if user.is_authenticated:
        if user in post.likes.all():
            return HttpResponse('you are like this post already!')
        post.likes.add(user)
        return redirect('detail', postid)
    else:
        return HttpResponse('you are not allow to like this post')
        
def PostUnlike(request, postid):
    post = Blog.objects.get(id = postid)
    user = request.user
    if user.is_authenticated:
        if user in post.likes.all():
            post.likes.remove(user)
            return redirect('detail', postid)
        else:
            return HttpResponse('you are not like this post')
    else:
        return HttpResponse('you are not allow to like this post')

    

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>login</h1>
    <form action="" method="POST">
        {{form}}
        {% csrf_token %}
        <button type="submit">login</button>
    </form>
</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>signup</h1>
    <form action="" method="POST">
        {{form}}
        {% csrf_token %}
        <button type="submit">sign up</button>
    </form>
</body>
</html>

testapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}title{% endblock title %}</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'testapp/style.css' %}">
</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">about us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">contact us</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <br/>
    
    {% block content %}{% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

testapp/templates/testapp/BlogDetail.html
{% extends 'base.html' %}

{% block title %}
{{blog.title}}
{% endblock title %}

{% block content %}
<h1>
    {{blog.title}}
</h1>

{% if user in blog.likes.all %}
    <a href="{% url 'postunlike' blog.id %}">unlike</a>
{% else %}
   <a href="{% url 'postlike' blog.id %}">like</a>
{% endif %}

<p>
    {{blog.content}}
    {{blog.date}}
</p>
<img style="width: 300px;" src="{{blog.image.url}}" alt="">
{% endblock content %}

testapp/templates/testapp/Home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <h1>{{user.username}}</h1>
{% endif %}





<ul>
    {% for post in blogpost %}           
                  <div class="card" style="width: 18rem;">
                    <img src="{{post.image.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{post.title}}</h5>
                      <p class="card-text">{{post.content}}</p>
                      <a href="{% url 'detail' post.id %}" class="btn btn-primary">detail</a>
                    </div>
                  </div>

    {% endfor %}
</ul>

    <a href="additem">add item</a>


{% if user.is_authenticated %}
    <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <button type="submit">logout</button>
    </form>
{% endif %}

{% load static %}

{% endblock content %}

testapp/templates/testapp/addItem.html
{%extends 'base.html'%}
{% block title %}add item{% endblock %}

{% block content %}
<form enctype="multipart/form-data" action="{% url 'additem' %}" method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">send</button>
</form>
{% endblock %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form enctype="multipart/form-data" action="{% url 'additem' %}" method="POST">
        {% csrf_token %}
        {{form}}
        <button type="submit">send</button>
    </form>
</body>
</html> -->